verus_git_url = "https://github.com/catoverflow/verus.git"
verus_refspec = "parallel"
verus_features = ["singular"]
verus_extra_verus_args = ["--no-report-long-running", "--num-threads", "4"]

[[project]]
name = "anvil"
git_url = "https://github.com/anvil-verifier/anvil"
refspec = "00f9660d71586479bd3ba4f74589bcc1f3183384"
crate_roots = ["src/esr_composition.rs"]
extra_verus_args = ["--crate-type=lib",
              "-L", "dependency=src/deps_hack/target/debug/deps",
              "--extern=deps_hack=src/deps_hack/target/debug/libdeps_hack.rlib",
              "--verify-module", "vreplicaset_controller",
              "--rlimit", "50",
              "-A", "warnings"]
prepare_script = """
pushd src/deps_hack
cargo clean
cargo build
popd
"""
